/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SpeakersIndexRouteImport } from './routes/speakers/index'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as OfflineIndexRouteImport } from './routes/offline/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as LiveIndexRouteImport } from './routes/live/index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks/index'
import { Route as TypeSlugRouteImport } from './routes/type/$slug'
import { Route as TrackSlugRouteImport } from './routes/track/$slug'
import { Route as SpeakersSlugRouteImport } from './routes/speakers/$slug'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as ProfileYearInReviewRouteImport } from './routes/profile/year-in-review'
import { Route as EventSlugRouteImport } from './routes/event/$slug'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as ApiProxySubtitlesRouteImport } from './routes/api/proxy/subtitles'
import { Route as ApiAuthUpgradeMastodonRouteImport } from './routes/api/auth/upgrade-mastodon'
import { Route as ApiAuthUpgradeGitlabRouteImport } from './routes/api/auth/upgrade-gitlab'
import { Route as ApiAuthUpgradeGithubRouteImport } from './routes/api/auth/upgrade-github'
import { Route as ApiAuthUpgradeDiscordRouteImport } from './routes/api/auth/upgrade-discord'
import { Route as ApiAuthMastodonRouteImport } from './routes/api/auth/mastodon'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGuestRouteImport } from './routes/api/auth/guest'
import { Route as ApiAuthGitlabRouteImport } from './routes/api/auth/gitlab'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth/discord'
import { Route as ApiProxyRoomsStatusRouteImport } from './routes/api/proxy/rooms/status'
import { Route as ApiAuthCallbackMastodonRouteImport } from './routes/api/auth/callback.mastodon'
import { Route as ApiAuthCallbackGitlabRouteImport } from './routes/api/auth/callback.gitlab'
import { Route as ApiAuthCallbackGithubRouteImport } from './routes/api/auth/callback.github'
import { Route as ApiAuthCallbackDiscordRouteImport } from './routes/api/auth/callback.discord'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineIndexRoute = OfflineIndexRouteImport.update({
  id: '/offline/',
  path: '/offline/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeSlugRoute = TypeSlugRouteImport.update({
  id: '/type/$slug',
  path: '/type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSlugRoute = TrackSlugRouteImport.update({
  id: '/track/$slug',
  path: '/track/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/speakers/$slug',
  path: '/speakers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileYearInReviewRoute = ProfileYearInReviewRouteImport.update({
  id: '/profile/year-in-review',
  path: '/profile/year-in-review',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySubtitlesRoute = ApiProxySubtitlesRouteImport.update({
  id: '/api/proxy/subtitles',
  path: '/api/proxy/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUpgradeMastodonRoute = ApiAuthUpgradeMastodonRouteImport.update({
  id: '/api/auth/upgrade-mastodon',
  path: '/api/auth/upgrade-mastodon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUpgradeGitlabRoute = ApiAuthUpgradeGitlabRouteImport.update({
  id: '/api/auth/upgrade-gitlab',
  path: '/api/auth/upgrade-gitlab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUpgradeGithubRoute = ApiAuthUpgradeGithubRouteImport.update({
  id: '/api/auth/upgrade-github',
  path: '/api/auth/upgrade-github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUpgradeDiscordRoute = ApiAuthUpgradeDiscordRouteImport.update({
  id: '/api/auth/upgrade-discord',
  path: '/api/auth/upgrade-discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMastodonRoute = ApiAuthMastodonRouteImport.update({
  id: '/api/auth/mastodon',
  path: '/api/auth/mastodon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGuestRoute = ApiAuthGuestRouteImport.update({
  id: '/api/auth/guest',
  path: '/api/auth/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGitlabRoute = ApiAuthGitlabRouteImport.update({
  id: '/api/auth/gitlab',
  path: '/api/auth/gitlab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoomsStatusRoute = ApiProxyRoomsStatusRouteImport.update({
  id: '/api/proxy/rooms/status',
  path: '/api/proxy/rooms/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackMastodonRoute = ApiAuthCallbackMastodonRouteImport.update({
  id: '/api/auth/callback/mastodon',
  path: '/api/auth/callback/mastodon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGitlabRoute = ApiAuthCallbackGitlabRouteImport.update({
  id: '/api/auth/callback/gitlab',
  path: '/api/auth/callback/gitlab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGithubRoute = ApiAuthCallbackGithubRouteImport.update({
  id: '/api/auth/callback/github',
  path: '/api/auth/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackDiscordRoute = ApiAuthCallbackDiscordRouteImport.update({
  id: '/api/auth/callback/discord',
  path: '/api/auth/callback/discord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event/$slug': typeof EventSlugRoute
  '/profile/year-in-review': typeof ProfileYearInReviewRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/track/$slug': typeof TrackSlugRoute
  '/type/$slug': typeof TypeSlugRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/live': typeof LiveIndexRoute
  '/map': typeof MapIndexRoute
  '/offline': typeof OfflineIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/search': typeof SearchIndexRoute
  '/signin': typeof SigninIndexRoute
  '/speakers': typeof SpeakersIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/gitlab': typeof ApiAuthGitlabRoute
  '/api/auth/guest': typeof ApiAuthGuestRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/mastodon': typeof ApiAuthMastodonRoute
  '/api/auth/upgrade-discord': typeof ApiAuthUpgradeDiscordRoute
  '/api/auth/upgrade-github': typeof ApiAuthUpgradeGithubRoute
  '/api/auth/upgrade-gitlab': typeof ApiAuthUpgradeGitlabRoute
  '/api/auth/upgrade-mastodon': typeof ApiAuthUpgradeMastodonRoute
  '/api/proxy/subtitles': typeof ApiProxySubtitlesRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/api/auth/callback/discord': typeof ApiAuthCallbackDiscordRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/auth/callback/gitlab': typeof ApiAuthCallbackGitlabRoute
  '/api/auth/callback/mastodon': typeof ApiAuthCallbackMastodonRoute
  '/api/proxy/rooms/status': typeof ApiProxyRoomsStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event/$slug': typeof EventSlugRoute
  '/profile/year-in-review': typeof ProfileYearInReviewRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/track/$slug': typeof TrackSlugRoute
  '/type/$slug': typeof TypeSlugRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/live': typeof LiveIndexRoute
  '/map': typeof MapIndexRoute
  '/offline': typeof OfflineIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/search': typeof SearchIndexRoute
  '/signin': typeof SigninIndexRoute
  '/speakers': typeof SpeakersIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/gitlab': typeof ApiAuthGitlabRoute
  '/api/auth/guest': typeof ApiAuthGuestRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/mastodon': typeof ApiAuthMastodonRoute
  '/api/auth/upgrade-discord': typeof ApiAuthUpgradeDiscordRoute
  '/api/auth/upgrade-github': typeof ApiAuthUpgradeGithubRoute
  '/api/auth/upgrade-gitlab': typeof ApiAuthUpgradeGitlabRoute
  '/api/auth/upgrade-mastodon': typeof ApiAuthUpgradeMastodonRoute
  '/api/proxy/subtitles': typeof ApiProxySubtitlesRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/api/auth/callback/discord': typeof ApiAuthCallbackDiscordRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/auth/callback/gitlab': typeof ApiAuthCallbackGitlabRoute
  '/api/auth/callback/mastodon': typeof ApiAuthCallbackMastodonRoute
  '/api/proxy/rooms/status': typeof ApiProxyRoomsStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event/$slug': typeof EventSlugRoute
  '/profile/year-in-review': typeof ProfileYearInReviewRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/track/$slug': typeof TrackSlugRoute
  '/type/$slug': typeof TypeSlugRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/live/': typeof LiveIndexRoute
  '/map/': typeof MapIndexRoute
  '/offline/': typeof OfflineIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/discord': typeof ApiAuthDiscordRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/gitlab': typeof ApiAuthGitlabRoute
  '/api/auth/guest': typeof ApiAuthGuestRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/mastodon': typeof ApiAuthMastodonRoute
  '/api/auth/upgrade-discord': typeof ApiAuthUpgradeDiscordRoute
  '/api/auth/upgrade-github': typeof ApiAuthUpgradeGithubRoute
  '/api/auth/upgrade-gitlab': typeof ApiAuthUpgradeGitlabRoute
  '/api/auth/upgrade-mastodon': typeof ApiAuthUpgradeMastodonRoute
  '/api/proxy/subtitles': typeof ApiProxySubtitlesRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/api/auth/callback/discord': typeof ApiAuthCallbackDiscordRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/auth/callback/gitlab': typeof ApiAuthCallbackGitlabRoute
  '/api/auth/callback/mastodon': typeof ApiAuthCallbackMastodonRoute
  '/api/proxy/rooms/status': typeof ApiProxyRoomsStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/event/$slug'
    | '/profile/year-in-review'
    | '/rooms/$roomId'
    | '/speakers/$slug'
    | '/track/$slug'
    | '/type/$slug'
    | '/bookmarks'
    | '/live'
    | '/map'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/rooms'
    | '/search'
    | '/signin'
    | '/speakers'
    | '/terms'
    | '/api/auth/discord'
    | '/api/auth/github'
    | '/api/auth/gitlab'
    | '/api/auth/guest'
    | '/api/auth/logout'
    | '/api/auth/mastodon'
    | '/api/auth/upgrade-discord'
    | '/api/auth/upgrade-github'
    | '/api/auth/upgrade-gitlab'
    | '/api/auth/upgrade-mastodon'
    | '/api/proxy/subtitles'
    | '/profile/$userId'
    | '/api/auth/callback/discord'
    | '/api/auth/callback/github'
    | '/api/auth/callback/gitlab'
    | '/api/auth/callback/mastodon'
    | '/api/proxy/rooms/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event/$slug'
    | '/profile/year-in-review'
    | '/rooms/$roomId'
    | '/speakers/$slug'
    | '/track/$slug'
    | '/type/$slug'
    | '/bookmarks'
    | '/live'
    | '/map'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/rooms'
    | '/search'
    | '/signin'
    | '/speakers'
    | '/terms'
    | '/api/auth/discord'
    | '/api/auth/github'
    | '/api/auth/gitlab'
    | '/api/auth/guest'
    | '/api/auth/logout'
    | '/api/auth/mastodon'
    | '/api/auth/upgrade-discord'
    | '/api/auth/upgrade-github'
    | '/api/auth/upgrade-gitlab'
    | '/api/auth/upgrade-mastodon'
    | '/api/proxy/subtitles'
    | '/profile/$userId'
    | '/api/auth/callback/discord'
    | '/api/auth/callback/github'
    | '/api/auth/callback/gitlab'
    | '/api/auth/callback/mastodon'
    | '/api/proxy/rooms/status'
  id:
    | '__root__'
    | '/'
    | '/event/$slug'
    | '/profile/year-in-review'
    | '/rooms/$roomId'
    | '/speakers/$slug'
    | '/track/$slug'
    | '/type/$slug'
    | '/bookmarks/'
    | '/live/'
    | '/map/'
    | '/offline/'
    | '/privacy/'
    | '/profile/'
    | '/rooms/'
    | '/search/'
    | '/signin/'
    | '/speakers/'
    | '/terms/'
    | '/api/auth/discord'
    | '/api/auth/github'
    | '/api/auth/gitlab'
    | '/api/auth/guest'
    | '/api/auth/logout'
    | '/api/auth/mastodon'
    | '/api/auth/upgrade-discord'
    | '/api/auth/upgrade-github'
    | '/api/auth/upgrade-gitlab'
    | '/api/auth/upgrade-mastodon'
    | '/api/proxy/subtitles'
    | '/profile/$userId/'
    | '/api/auth/callback/discord'
    | '/api/auth/callback/github'
    | '/api/auth/callback/gitlab'
    | '/api/auth/callback/mastodon'
    | '/api/proxy/rooms/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventSlugRoute: typeof EventSlugRoute
  ProfileYearInReviewRoute: typeof ProfileYearInReviewRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  TrackSlugRoute: typeof TrackSlugRoute
  TypeSlugRoute: typeof TypeSlugRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  OfflineIndexRoute: typeof OfflineIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiAuthGitlabRoute: typeof ApiAuthGitlabRoute
  ApiAuthGuestRoute: typeof ApiAuthGuestRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMastodonRoute: typeof ApiAuthMastodonRoute
  ApiAuthUpgradeDiscordRoute: typeof ApiAuthUpgradeDiscordRoute
  ApiAuthUpgradeGithubRoute: typeof ApiAuthUpgradeGithubRoute
  ApiAuthUpgradeGitlabRoute: typeof ApiAuthUpgradeGitlabRoute
  ApiAuthUpgradeMastodonRoute: typeof ApiAuthUpgradeMastodonRoute
  ApiProxySubtitlesRoute: typeof ApiProxySubtitlesRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
  ApiAuthCallbackDiscordRoute: typeof ApiAuthCallbackDiscordRoute
  ApiAuthCallbackGithubRoute: typeof ApiAuthCallbackGithubRoute
  ApiAuthCallbackGitlabRoute: typeof ApiAuthCallbackGitlabRoute
  ApiAuthCallbackMastodonRoute: typeof ApiAuthCallbackMastodonRoute
  ApiProxyRoomsStatusRoute: typeof ApiProxyRoomsStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline/': {
      id: '/offline/'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type/$slug': {
      id: '/type/$slug'
      path: '/type/$slug'
      fullPath: '/type/$slug'
      preLoaderRoute: typeof TypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$slug': {
      id: '/track/$slug'
      path: '/track/$slug'
      fullPath: '/track/$slug'
      preLoaderRoute: typeof TrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/speakers/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/year-in-review': {
      id: '/profile/year-in-review'
      path: '/profile/year-in-review'
      fullPath: '/profile/year-in-review'
      preLoaderRoute: typeof ProfileYearInReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/subtitles': {
      id: '/api/proxy/subtitles'
      path: '/api/proxy/subtitles'
      fullPath: '/api/proxy/subtitles'
      preLoaderRoute: typeof ApiProxySubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/upgrade-mastodon': {
      id: '/api/auth/upgrade-mastodon'
      path: '/api/auth/upgrade-mastodon'
      fullPath: '/api/auth/upgrade-mastodon'
      preLoaderRoute: typeof ApiAuthUpgradeMastodonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/upgrade-gitlab': {
      id: '/api/auth/upgrade-gitlab'
      path: '/api/auth/upgrade-gitlab'
      fullPath: '/api/auth/upgrade-gitlab'
      preLoaderRoute: typeof ApiAuthUpgradeGitlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/upgrade-github': {
      id: '/api/auth/upgrade-github'
      path: '/api/auth/upgrade-github'
      fullPath: '/api/auth/upgrade-github'
      preLoaderRoute: typeof ApiAuthUpgradeGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/upgrade-discord': {
      id: '/api/auth/upgrade-discord'
      path: '/api/auth/upgrade-discord'
      fullPath: '/api/auth/upgrade-discord'
      preLoaderRoute: typeof ApiAuthUpgradeDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/mastodon': {
      id: '/api/auth/mastodon'
      path: '/api/auth/mastodon'
      fullPath: '/api/auth/mastodon'
      preLoaderRoute: typeof ApiAuthMastodonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/guest': {
      id: '/api/auth/guest'
      path: '/api/auth/guest'
      fullPath: '/api/auth/guest'
      preLoaderRoute: typeof ApiAuthGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/gitlab': {
      id: '/api/auth/gitlab'
      path: '/api/auth/gitlab'
      fullPath: '/api/auth/gitlab'
      preLoaderRoute: typeof ApiAuthGitlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/rooms/status': {
      id: '/api/proxy/rooms/status'
      path: '/api/proxy/rooms/status'
      fullPath: '/api/proxy/rooms/status'
      preLoaderRoute: typeof ApiProxyRoomsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/mastodon': {
      id: '/api/auth/callback/mastodon'
      path: '/api/auth/callback/mastodon'
      fullPath: '/api/auth/callback/mastodon'
      preLoaderRoute: typeof ApiAuthCallbackMastodonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/gitlab': {
      id: '/api/auth/callback/gitlab'
      path: '/api/auth/callback/gitlab'
      fullPath: '/api/auth/callback/gitlab'
      preLoaderRoute: typeof ApiAuthCallbackGitlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/github': {
      id: '/api/auth/callback/github'
      path: '/api/auth/callback/github'
      fullPath: '/api/auth/callback/github'
      preLoaderRoute: typeof ApiAuthCallbackGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/discord': {
      id: '/api/auth/callback/discord'
      path: '/api/auth/callback/discord'
      fullPath: '/api/auth/callback/discord'
      preLoaderRoute: typeof ApiAuthCallbackDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventSlugRoute: EventSlugRoute,
  ProfileYearInReviewRoute: ProfileYearInReviewRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  SpeakersSlugRoute: SpeakersSlugRoute,
  TrackSlugRoute: TrackSlugRoute,
  TypeSlugRoute: TypeSlugRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  MapIndexRoute: MapIndexRoute,
  OfflineIndexRoute: OfflineIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiAuthGitlabRoute: ApiAuthGitlabRoute,
  ApiAuthGuestRoute: ApiAuthGuestRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMastodonRoute: ApiAuthMastodonRoute,
  ApiAuthUpgradeDiscordRoute: ApiAuthUpgradeDiscordRoute,
  ApiAuthUpgradeGithubRoute: ApiAuthUpgradeGithubRoute,
  ApiAuthUpgradeGitlabRoute: ApiAuthUpgradeGitlabRoute,
  ApiAuthUpgradeMastodonRoute: ApiAuthUpgradeMastodonRoute,
  ApiProxySubtitlesRoute: ApiProxySubtitlesRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
  ApiAuthCallbackDiscordRoute: ApiAuthCallbackDiscordRoute,
  ApiAuthCallbackGithubRoute: ApiAuthCallbackGithubRoute,
  ApiAuthCallbackGitlabRoute: ApiAuthCallbackGitlabRoute,
  ApiAuthCallbackMastodonRoute: ApiAuthCallbackMastodonRoute,
  ApiProxyRoomsStatusRoute: ApiProxyRoomsStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
