// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	R2: R2Bucket;
	YEAR?: string;
	DEFAULT_YEAR?: string;
	BUILD_YEAR?: string;
}
